dist: trusty
language: java
jdk:
 - openjdk13

before_install:
  - wget http://ftp.meisei-u.ac.jp/mirror/apache/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v

install: true

script:
 - cd fixmycity
 - mvn clean javafx:compile -Pcoverage sonar:sonar -Dsonar.organization=progettoispw2019 -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=progettoIspw2019_FixMyCity -Dsonar.host.url=https://sonarcloud.io
